server:
  port: 8761

info:
  component: Discovery Server

eureka:
  # Configure standalone mode
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: discovery
  profiles:
    active: native